name: deploy

on:
  push:
    branches:
      - main

env:
  PLATFORMS: linux/arm64,linux/amd64

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.66.0
      id: tagging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        DEFAULT_BUMP: minor
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: semver
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ github.repository }}:latest,${{ github.repository }}:${{ needs.semver.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}